### PR TITLE
#75 Split <option> value by spaces for javafx:run

### LINKED ISSUE #75: Unable to run profiler
I'm using an IDE, it provide a property, ${vm.args} that I try to use with the javafx-maven-plugin like:
```
    <execution>
        <!-- Configuration for automatic IDE profiling -->
        <id>ide-profile</id>
        <configuration>
            <options>
                <option>${vm.args}</option>
            </options>
            <mainClass>com.raelity.play.xs13.App</mainClass>
        </configuration>
    </execution>
```
Typically vm.args looks like `-XX:+He... -XX:Hea... -agentp...` and it gets treated as a single jvm argument which fails. It needs to be split by whitespace. 

I could be missing the right way to do this. I was wondering about extending the plugin; something like: 
`<optionsString><string>${vm.args}</string></optionsString>`
which would split the string, by default on white space, and add the resulting list to vm options.

BTW, manually taking the value of ${vm.args} and adding them separately as `<option>arg</option>` works and the profiler run OK.

### PR DESCRIPTION
**Pull request by betanzos**
When `javafx:jlink` command creates the luncher all <option> values are joined using an space like separator, because of this the luncher pass VM args in the right way. In the other hand for the command `javafx:run` the values of <option> are used as they are defined, but if this values contain spaces there are not handle well and the VM does not receive them correctly.

It is desirable that the behavior of both commands, regarding the treatment of the VM args, be the same.

This PR fix #75.

### CODE REVIEW

File: src/main/java/org/openjfx/JavaFXRunMojo.java [hunk 1]
```diff
@@ -127,6 +128,9 @@ public void execute() throws MojoExecutionException {
                     .filter(Objects::nonNull)
                     .filter(String.class::isInstance)
                     .map(String.class::cast)
+                    .map(s -> s.split(" "))
```
Comment (errael) [inline src/main/java/org/openjfx/JavaFXRunMojo.java:131]: Wouldn't split("\\s+") be more bulletproof? (There's two '\\' in a row)

Comment (betanzos) [reply src/main/java/org/openjfx/JavaFXRunMojo.java:131]: You're right

**Comment by errael** [comment]
> both commands, regarding the treatment of the VM args, be the same

I looked at both when I was first contemplating this problem. Now that I think of it, by the jlink copying into a string, if the source has quotes, then that get's handled automatically when the command is processed. That would also handle my case where there are multiple args.

**Comment by betanzos** [comment]
> I looked at both when I was first contemplating this problem. Now that I think of it, by the jlink copying into a string, if the source has quotes, then that get's handled automatically when the command is processed. That would also handle my case where there are multiple args.

Yes, in the case of `jlink` there is no problem because as you say everything is concatenated into a string and we don't need to process the arguments, but with `run` does.

**Comment by errael** [comment]
Cloned the betanzos repository. 0.0.5-SNAPSHOT works well with the IDE profiling feature.

File: src/main/java/org/openjfx/JavaFXRunMojo.java [hunk 2]
```diff
@@ -127,6 +129,8 @@ public void execute() throws MojoExecutionException {
                     .filter(Objects::nonNull)
                     .filter(String.class::isInstance)
                     .map(String.class::cast)
+                    .map(this::splitComplexArgumentString)
```
Comment (abhinayagarwal) [inline src/main/java/org/openjfx/JavaFXRunMojo.java:132]: The new method can easily break. Would it be possible to add a few JUnit tests which can validate the functionality?

Comment (betanzos) [reply src/main/java/org/openjfx/JavaFXRunMojo.java:132]: Done!
