### PR TITLE
#68 Automatically compile project before execute javafx:jlink goal, if needed

### LINKED ISSUE #68: javafx:jlink goal requires manual compile
Unlike javafx:run, if javafx:jlink is executed without compile manually the project this goal fail

> [ERROR] Failed to execute goal org.openjfx:javafx-maven-plugin:0.0.4:jlink (default-cli) on project test-project: Error: Output directory is empty, compile first -> [Help 1]

### PR DESCRIPTION
**Pull request by betanzos**
Compilation is carried out through the Maven compile phase instead the goal compiler:compile. Because of this, any goal associated with said phase will also be executed.

Fixes #68

### CODE REVIEW

File: src/main/java/org/openjfx/JavaFXBaseMojo.java [hunk 1]
```diff
@@ -177,20 +177,7 @@ void preparePaths(Path jdkHome) throws MojoExecutionException {
         }
 
         String outputDirectory = project.getBuild().getOutputDirectory();
-        if (outputDirectory == null || outputDirectory.isEmpty()) {
-            throw new MojoExecutionException("Output directory doesn't exist, compile first");
```
Comment (jperedadnr) [inline src/main/java/org/openjfx/JavaFXBaseMojo.java]: In theory, the compiler plugin will do its job, and `target` shouldn't be null. However this is a sanity check to prevent any possible situation where target is removed even after compile creates it? Maybe we can rephrase the message instead?

File: src/main/java/org/openjfx/JavaFXBaseMojo.java [hunk 2]
```diff
@@ -177,20 +177,7 @@ void preparePaths(Path jdkHome) throws MojoExecutionException {
...
-        }
-
         File[] classes = new File(outputDirectory).listFiles();
-        if (classes == null || classes.length == 0) {
-            getLog().debug("Output directory was empty, compiling...");
-            classes = new File(outputDirectory).listFiles();
-            if (classes == null || classes.length == 0) {
```
Comment (jperedadnr) [inline src/main/java/org/openjfx/JavaFXBaseMojo.java]: remove these three lines only

File: src/main/java/org/openjfx/JavaFXBaseMojo.java [hunk 3]
```diff
@@ -177,20 +177,7 @@ void preparePaths(Path jdkHome) throws MojoExecutionException {
...
-                throw new MojoExecutionException("Output directory is empty, compile first");
```
Comment (jperedadnr) [inline src/main/java/org/openjfx/JavaFXBaseMojo.java]: keep the exception, rephrasing the message, to prevent a possible NPE if classes is null or empty.

File: src/main/java/org/openjfx/JavaFXBaseMojo.java [hunk 4]
```diff
@@ -177,20 +177,7 @@ void preparePaths(Path jdkHome) throws MojoExecutionException {
...
-            }
-        } else {
-            // TODO: verify if classes require compiling
-        }
```
Comment (jperedadnr) [inline src/main/java/org/openjfx/JavaFXBaseMojo.java]: This can be safely removed

File: src/main/java/org/openjfx/JavaFXBaseMojo.java (hunk 1 above)
Comment (betanzos) [reply src/main/java/org/openjfx/JavaFXBaseMojo.java]: Agree.

What do you think of this message: "Output directory doesn't exist after compile"

File: src/main/java/org/openjfx/JavaFXBaseMojo.java (hunk 2 above)
Comment (betanzos) [reply src/main/java/org/openjfx/JavaFXBaseMojo.java]: OK

File: src/main/java/org/openjfx/JavaFXBaseMojo.java (hunk 3 above)
Comment (betanzos) [reply src/main/java/org/openjfx/JavaFXBaseMojo.java]: Agree.

File: src/main/java/org/openjfx/JavaFXBaseMojo.java (hunk 1 above)
Comment (jperedadnr) [reply src/main/java/org/openjfx/JavaFXBaseMojo.java]: I would just say "Error: Output directory doesn't exist"
